
create table contacts (
	id int (8) NOT NULL DEFAULT 0,
	FN varchar (64),
	SOUND varchar (64),
	ORG_Name varchar (64),
	ORG_Unit varchar (64),
	TITLE varchar (64),
	N_Family varchar (64),
	N_Given varchar (64),
	N_Middle varchar (64),
	N_Prefix varchar (64),
	N_Suffix varchar (64),
	LABEL text,
	ADR_POAddr varchar (64),
	ADR_ExtAddr varchar (64),
	ADR_Street varchar (64),
	ADR_Locality varchar (32),
	ADR_Region varchar (32),
	ADR_PostalCode varchar (32),
	ADR_CountryName varchar (32),
	ADR_Work enum('y','n') NOT NULL DEFAULT 'n',
	ADR_Home enum('y','n') NOT NULL DEFAULT 'n',
	ADR_Parcel enum('y','n') NOT NULL DEFAULT 'n',
	ADR_Postal enum('y','n') NOT NULL DEFAULT 'n',
	TZ varchar (8),
	GEO varchar (32),
	A_TEL varchar (40) NOT NULL DEFAULT "+1 (000) 000-0000",
	A_TEL_Work enum('y','n') NOT NULL DEFAULT 'n',
	A_TEL_Home enum('y','n') NOT NULL DEFAULT 'n',
	A_TEL_Voice enum('y','n') NOT NULL DEFAULT 'n',
	A_TEL_Msg enum('y','n') NOT NULL DEFAULT 'n',
	A_TEL_Fax enum('y','n') NOT NULL DEFAULT 'n',
	A_TEL_Prefer enum('y','n') NOT NULL DEFAULT 'n',
	B_TEL varchar (40) NOT NULL DEFAULT "+1 (000) 000-0000",
	B_TEL_Work enum('y','n') NOT NULL DEFAULT 'n',
	B_TEL_Home enum('y','n') NOT NULL DEFAULT 'n',
	B_TEL_Voice enum('y','n') NOT NULL DEFAULT 'n',
	B_TEL_Msg enum('y','n') NOT NULL DEFAULT 'n',
	B_TEL_Fax enum('y','n') NOT NULL DEFAULT 'n',
	B_TEL_Prefer enum('y','n') NOT NULL DEFAULT 'n',
	C_TEL varchar (40) NOT NULL DEFAULT "+1 (000) 000-0000",
	C_TEL_Work enum('y','n') NOT NULL DEFAULT 'n',
	C_TEL_Home enum('y','n') NOT NULL DEFAULT 'n',
	C_TEL_Voice enum('y','n') NOT NULL DEFAULT 'n',
	C_TEL_Msg enum('y','n') NOT NULL DEFAULT 'n',
	C_TEL_Fax enum('y','n') NOT NULL DEFAULT 'n',
	C_TEL_Prefer enum('y','n') NOT NULL DEFAULT 'n',
	D_EMAILTYPE enum('INTERNET','CompuServe','AOL','Prodigy','eWorld','AppleLink','AppleTalk','PowerShare','IBMMail','ATTMail','MCIMail','X.400','TLX') NOT NULL DEFAULT "INTERNET",
	D_EMAIL varchar (64),
	D_EMAIL_Work enum('y','n') NOT NULL DEFAULT 'n',
	D_EMAIL_Home enum('y','n') NOT NULL DEFAULT 'n',
	PRIMARY KEY (id),
	UNIQUE id (id)
);
