<?php
/**
	* eGroupWare - eTemplates for Application felamimail
	* http://www.egroupware.org
	* generated by soetemplate::dump4setup() 2009-08-15 00:10
	*
	* @license http://opensource.org/licenses/gpl-license.php GPL - GNU General Public License
	* @package felamimail
	* @subpackage setup
	* @version $Id: class.soetemplate.inc.php 27222 2009-06-08 16:21:14Z ralfbecker $
	*/

$templ_version=1;

$templ_data[] = array('name' => 'felamimail.stationery.sample','template' => '','lang' => '','group' => '0','version' => '1.7.003','data' => 'a:1:{i:0;a:6:{s:4:"type";s:4:"grid";s:4:"data";a:4:{i:0;a:0:{}i:1;a:1:{s:1:"A";a:3:{s:4:"type";s:5:"label";s:4:"span";s:7:",header";s:5:"label";s:6:"Header";}}i:2;a:1:{s:1:"A";a:4:{s:4:"type";s:4:"html";s:4:"name";s:7:"message";s:4:"span";s:8:",message";s:5:"label";s:7:"message";}}i:3;a:1:{s:1:"A";a:4:{s:4:"type";s:4:"html";s:4:"name";s:9:"signature";s:4:"span";s:10:",signature";s:5:"label";s:9:"signature";}}}s:4:"rows";i:3;s:4:"cols";i:1;s:4:"size";s:21:"100%,,0,fullwidth,0,0";s:7:"options";a:5:{i:3;s:9:"fullwidth";i:0;s:4:"100%";i:4;s:1:"0";i:5;s:1:"0";i:2;s:1:"0";}}}','size' => '100%,,0,fullwidth,0,0','style' => 'body {
 font-family: "Lucida Grande";
 font-size: 12px;
 color: #000000;
 background-color: #eaeaea;
 margin: 0;
 padding: 0;
}

table.fullwidth {
 table-layout:fixed;
 width: 100%;
 margin: 0;
 padding: 0;
 border: 0;
}

td.header {
 background-color: #322f40;
 color: #ffffff;
 font-weight: bold;
 margin: 0;
 padding: 1em;
 border-left: 6px solid #504a66;
 border-bottom: 1px solid #504a66;
}

td.message {
 margin: 0.5em;
 padding: 1em;
 color: #333333;
 font-family: "Lucida Grande";
 font-size: 12px;
}

td.signature {
 color: #666666;
 border-left: 5px solid #747474;
 margin: 0.5em;
 padding-left: 8px;
 font-family: "Lucida Grande";
 font-size: 12px;
}

img {
 border: 0;
 margin: 0;
 padding: 0;
}
','modified' => '1250287711',);

