REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'low','common','en','Low');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'forum','common','en','Forum');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'normal','common','en','Normal');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'medium','common','en','Medium');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'high','common','en','High');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'add','common','en','Add');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'create','common','en','Create');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'edit','common','en','Edit');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'copy','common','en','Copy');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'rename','common','en','Rename');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'delete','common','en','Delete');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'done','common','en','Done');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'change','common','en','Change');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'clear form','common','en','Clear Form');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'total','common','en','Total');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'view','common','en','View');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'save','common','en','Save');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'submit','common','en','Submit');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'search','common','en','Search');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'cancel','common','en','Cancel');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'exit','common','en','Exit');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'yes','common','en','Yes');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'no','common','en','No');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'ok','common','en','OK');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'clear','common','en','Clear');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'january','common','en','January');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'february','common','en','February');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'march','common','en','March');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'april','common','en','April');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'may','common','en','May');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'june','common','en','June');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'july','common','en','July');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'august','common','en','August');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'september','common','en','September');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'october','common','en','October');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'november','common','en','November');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'december','common','en','December');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'monday','common','en','Monday');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'tuesday','common','en','Tuesday');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'wednesday','common','en','Wednesday');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'thursday','common','en','Thursday');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'friday','common','en','Friday');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'saturday','common','en','Saturday');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'sunday','common','en','Sunday');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'access','common','en','Access');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'private','common','en','Private');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'access type','common','en','Access type');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'group access','common','en','Group Access');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'global public','common','en','Global Public');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'group public','common','en','Group Public');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'which groups','common','en','which groups');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'created by','common','en','Created By');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'administration','common','en','Administration');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'inventory','common','en','Inventory');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'todo list','common','en','Todo List');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'calendar','common','en','calendar');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'bookmarks','common','en','Bookmarks');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'addressbook','common','en','Addressbook');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'e-mail','common','en','E-Mail');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'chat','common','en','Chat');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'preferences','common','en','Preferences');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'login','common','en','Login');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'logout','common','en','Logout');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'first name','common','en','First name');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'last name','common','en','Last name');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'admin','common','en','Admin');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'email','common','en','E-Mail');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'headlines','common','en','Headlines');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'nntp','common','en','NNTP');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'groups','common','en','Groups');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'book marks','common','en','Book marks');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'name','common','en','Name');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'file manager','common','en','File manager');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'ftp','common','en','FTP');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'password','common','en','Password');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'date','common','en','Date');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'time','common','en','Time');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'priority','common','en','Priority');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'help','common','en','Help');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'error','common','en','Error');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'updated','common','en','Updated');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'home','common','en','Home');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'users','common','en','users');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'news headlines','common','en','News headlines');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'news reader','common','en','News Reader');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'human resources','common','en','Human Resources');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'address book','common','en','Address Book');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'current users','common','en','Current users');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'first page','common','en','first page');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'next page','common','en','next page');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'last page','common','en','last page');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'previous page','common','en','Previous page');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'filter','common','en','Filter');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'show all','common','en','show all');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'only yours','common','en','only yours');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'print','common','en','Print');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'trouble ticket system','common','en','Trouble Ticket System');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'you are required to change your password durring your first login','common','en','You are required to change your password durring your first login');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'powered by phpgroupware version x','common','en','Powered by <a href=http://www.phpgroupware.org>phpGroupWare</a> version %1');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'sorry, there was a problem processing your request.','common','en','Sorry, there was a problem processing your request.');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'your message has been sent','common','en','Your message has been sent');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'new entry added sucessfully','common','en','New entry added sucessfully');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'entry updated sucessfully','common','en','Entry updated sucessfully');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'entry has been deleted sucessfully','common','en','Entry has been deleted sucessfully');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'password has been updated','common','en','Password has been updated');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'session has been killed','common','en','Session has been killed');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'account has been updated','common','en','Account has been updated');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'account has been created','common','en','Account has been created');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'account has been deleted','common','en','Account has been deleted');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'error creating x x directory','common','en','Error creating %1%2 directory');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'error deleting x x directory','common','en','Error deleting %1%2 directory');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'error renaming x x directory','common','en','Error renaming %1%2 directory');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'please x by hand','common','en','Please %1 by hand');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'to correct this error for the future you will need to properly set the','common','en','To correct this error for the future you will need to properly set the');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'permissions to the files/users directory','common','en','permissions to the files/users directory');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'On *nix systems please type: x','common','en','On *nix systems please type: %1');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'your settings have been updated','common','en','Your settings have been Updated');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'group has been added','common','en','Group has been added');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'group has been deleted','common','en','Group has been deleted');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'group has been updated','common','en','Group has been updated');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'showing x - x of x','common','en','showing %1 - %2 of %3');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'showing x','common','en','showing %1');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'your search returned 1 match','common','en','your search returned 1 match');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'your search returned x matchs','common','en','your search returned %1 matchs');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'you have 1 new message!','common','en','You have 1 new message!');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'you have x new messages!','common','en','You have %1 new messages!');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'today is x\'s birthday!','common','en','Today is %1\'s birthday!');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'tommorow is x\'s birthday.','common','en','Tommorow is %1\'s birthday.');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'you have 1 high priority event on your calendar today.','common','en','You have 1 high priority event on your calendar today.');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'you have x high priority events on your calendar today.','common','en','You have %1 high priority events on your calendar today.');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'it has been more then x days since you changed your password','common','en','It has been more then %1 days since you changed your password');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'are you sure you want to delete this entry ?','common','en','Are you sure you want to delete this entry ?');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'are you sure you want to delete this entry ?','common','en','Are you sure you want to delete this entry ?');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'username','login','en','Username');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'password','login','en','Password');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'login','login','en','Login');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'use cookies','login','en','use cookies');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'you have been successfully logged out','login','en','You have been successfully logged out');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'sorry, your login has expired','login','en','Sorry, your login has expired');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'bad login or password','login','en','Bad login or password');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'your session could not be verified.','login','en','Your session could not be verified.');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'your session could not be verified.','login','en','Your session could not be verified.');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'address book','addressbook','en','Address Book');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'last name','addressbook','en','Last Name');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'first name','addressbook','en','First Name');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'e-mail','addressbook','en','E-Mail');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'home phone','addressbook','en','Home Phone');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'fax','addressbook','en','Fax');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'work phone','addressbook','en','Work Phone');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'pager','addressbook','en','Pager');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'mobile','addressbook','en','Mobile');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'other number','addressbook','en','Other Number');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'street','addressbook','en','Street');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'birthday','addressbook','en','Birthday');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'city','addressbook','en','City');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'state','addressbook','en','State');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'zip code','addressbook','en','ZIP Code');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'notes','addressbook','en','Notes');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'company name','addressbook','en','company name');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'company name','addressbook','en','company name');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'last x logins','admin','en','Last %1 logins');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'loginid','admin','en','LoginID');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'ip','admin','en','IP');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'total records','admin','en','Total records');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'user accounts','admin','en','User accounts');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'new group name','admin','en','New group name');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'create group','admin','en','Create Group');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'kill','admin','en','Kill');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'idle','admin','en','idle');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'login time','admin','en','Login Time');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'anonymous user','admin','en','Anonymous user');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'manager','admin','en','Manager');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'account active','admin','en','Account active');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 're-enter password','admin','en','Re-enter password');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'group name','admin','en','Group Name');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'display','admin','en','Display');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'base url','admin','en','Base URL');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'news file','admin','en','News File');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'minutes between reloads','admin','en','Minutes between Reloads');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'listings displayed','admin','en','Listings Displayed');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'news type','admin','en','News Type');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'user groups','admin','en','User groups');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'headline sites','admin','en','Headline Sites');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'network news','admin','en','Network News');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'site','admin','en','Site');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'view sessions','admin','en','View sessions');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'view access log','admin','en','View Access Log');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'active','admin','en','Active');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'disabled','admin','en','Disabled');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'last time read','admin','en','Last Time Read');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'permissions','admin','en','Permissions');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'title','admin','en','Title');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'enabled','admin','en','Enabled');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'applications','admin','en','Applications');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'edit group','admin','en','Edit Group');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'submit changes','admin','en','Submit Changes');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'you must add at least 1 permission to this account','admin','en','You must add at least 1 permission to this account');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'installed applications','admin','en','Installed applications');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'remove all users from this group','admin','en','Remove all users from this group');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'permissions this group has','admin','en','Permissions this group has');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'select permissions this group will have','admin','en','Select permissions this group will have');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'sorry, that group name has already been taking.','admin','en','Sorry, that group name has already been taking.');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'add new application','admin','en','Add new application');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'application name','admin','en','Application name');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'application title','admin','en','Application title');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'edit application','admin','en','Edit application');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'you must enter an application name and title.','admin','en','You must enter an application name and title.');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'are you sure you want to delete this application ?','admin','en','Are you sure you want to delete this application ?');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'are you sure you want to delete this group ?','admin','en','Are you sure you want to delete this group ?');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'are you sure you want to kill this session ?','admin','en','Are you sure you want to kill this session ?');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'all records and account information will be lost!','admin','en','All records and account information will be lost!');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'are you sure you want to delete this account ?','admin','en','Are you sure you want to delete this account ?');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'are you sure you want to delete this news site ?','admin','en','Are you sure you want to delete this news site ?');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'percent of users that logged out','admin','en','Percent of users that logged out');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'list of current users','admin','en','list of current users');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'new password [ leave blank for no change ]','admin','en','New password [ Leave blank for no change ]');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'the two passwords are not the same','admin','en','The two passwords are not the same');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'the login and password can not be the same','admin','en','The login and password can not be the same');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'you must enter a password','admin','en','You must enter a password');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'that loginid has already been taken','admin','en','That loginid has already been taken');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'you must enter a display','admin','en','You must enter a display');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'you must enter a base url','admin','en','You must enter a base url');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'you must enter a news url','admin','en','You must enter a news url');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'you must enter the number of minutes between reload','admin','en','You must enter the number of minutes between reload');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'you must enter the number of listings display','admin','en','You must enter the number of listings display');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'you must select a file type','admin','en','You must select a file type');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'that site has already been entered','admin','en','That site has already been entered');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'select users for inclusion','admin','en','Select users for inclusion');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'sorry, the follow users are still a member of the group x','admin','en','Sorry, the follow users are still a member of the group %1');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'they must be removed before you can continue','admin','en','They must be removed before you can continue');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'they must be removed before you can continue','admin','en','They must be removed before you can continue');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'today','calendar','en','Today');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'this week','calendar','en','This week');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'this month','calendar','en','This month');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'generate printer-friendly version','calendar','en','Generate printer-friendly version');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'printer friendly','calendar','en','Printer Friendly');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'you have not entered a\\nbrief description','calendar','en','You have not entered a\\nBrief Description');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'you have not entered a\\nvalid time of day.','calendar','en','You have not entered a\\nvalid time of day.');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'are you sure\\nyou want to\\ndelete this entry ?','calendar','en','Are you sure\\nyou want to\\ndelete this entry ?');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'participants','calendar','en','Participants');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'calendar - edit','calendar','en','Calendar - Edit');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'calendar - add','calendar','en','Calendar - Add');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'brief description','calendar','en','Brief Description');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'full description','calendar','en','Full Description');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'duration','calendar','en','Duration');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'minutes','calendar','en','minutes');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'repeat type','calendar','en','Repeat type');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'none','calendar','en','None');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'daily','calendar','en','Daily');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'weekly','calendar','en','weekly');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'monthly (by day)','calendar','en','Monthly (by day)');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'monthly (by date)','calendar','en','Monthly (by date)');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'yearly','calendar','en','Yearly');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'repeat end date','calendar','en','Repeat End date');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'use end date','calendar','en','Use End date');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'repeat day','calendar','en','Repeat day');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( '(for weekly)','calendar','en','(for Weekly)');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'frequency','calendar','en','Frequency');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'sun','calendar','en','Sun');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'mon','calendar','en','Mon');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'tue','calendar','en','Tue');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'wed','calendar','en','Wed');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'thu','calendar','en','Thu');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'fri','calendar','en','Fri');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'sat','calendar','en','Sat');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'su','calendar','en','Su');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'mo','calendar','en','M');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'tu','calendar','en','T');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'we','calendar','en','W');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'th','calendar','en','T');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'fr','calendar','en','F');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'sa','calendar','en','Sa');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'search results','calendar','en','Search Results');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'no matches found.','calendar','en','No matches found.');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( '1 match found','calendar','en','1 match found');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'x matches found','calendar','en','%1 matches found');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'description','calendar','en','Description');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'repetition','calendar','en','Repetition');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'days repeated','calendar','en','days repeated');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'go!','calendar','en','Go!');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'year','calendar','en','Year');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'month','calendar','en','Month');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'week','calendar','en','Week');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'new entry','calendar','en','New Entry');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'view this entry','calendar','en','View this entry');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'the following conflicts with the suggested time:<ul>x</ul>','calendar','en','The following conflicts with the suggested time:<ul>%1</ul>');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'your suggested time of <B> x - x </B> conflicts with the following existing calendar entries:','calendar','en','Your suggested time of <B> %1 - %2 </B> conflicts with the following existing calendar entries:');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'you must enter one or more search keywords','calendar','en','You must enter one or more search keywords');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'are you sure\\nyou want to\\ndelete this entry ?\\n\\nthis will delete\\nthis entry for all users.','calendar','en','Are you sure\\nyou want to\\ndelete this entry ?\\n\\nThis will delete\\nthis entry for all users.');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'a','calendar','en','');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'a','calendar','en','');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'a','calendar','en','');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'a','calendar','en','');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'a','calendar','en','');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'a','calendar','en','');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'a','calendar','en','');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'reply','email','en','Reply');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'reply all','email','en','Reply All');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'forward','email','en','Forward');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'delete','email','en','Delete');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'previous','email','en','Previous');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'next','email','en','Next');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'from','email','en','From');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'to','email','en','To');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'cc','email','en','CC');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'files','email','en','Files');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'date','email','en','Date');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'send','email','en','Send');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'subject','email','en','Subject');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'folder','email','en','Folder');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'size','email','en','Size');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'section','email','en','Section');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'image','email','en','Image');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'no subject','email','en','No Subject');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'compose','email','en','Compose');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'message','email','en','Message');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'messages','email','en','Messages');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'new message','email','en','New message');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'undisclosed sender','email','en','Undisclosed Sender');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'undisclosed recipients','email','en','Undisclosed Recipients');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'please select a message first','email','en','Please select a message first');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'this folder is empty','email','en','This folder is empty');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'switch current folder to','email','en','Switch Current Folder To');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'move selected messages into','email','en','Move Selected Messages into');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'add to addressbook','email','en','Add to addressbook');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( '1 message has been deleted','email','en','1 message has been deleted');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'x messages have been deleted','email','en','%1 messages have been deleted');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'monitor','email','en','Monitor');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'monitor','email','en','Monitor');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'usersfile_perm_error','filemanager','en','To correct this error you will need to properly set the permissions to the files/users directory.<BR> On *nix systems please type: chmod 707');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'groupsfile_perm_error','filemanager','en','To correct this error you will need to properly set the permissions to the files/groups directory.<BR> On *nix systems please type: chmod 707');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'private_files','filemanager','en','Private files');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'group_files','filemanager','en','group files');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'files','filemanager','en','Files');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'new_file','filemanager','en','New File');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'rename_to','filemanager','en','Rename to');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'file_upload','filemanager','en','File Upload');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'current_file','filemanager','en','Current File');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'clipboard_contents','filemanager','en','Clipboard Contents');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'copy_as','filemanager','en','Copy as');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'create','filemanager','en','Create');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'edit','filemanager','en','Edit');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'copy','filemanager','en','Copy');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'delete','filemanager','en','Delete');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'do_delete','filemanager','en','Delete');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'rename','filemanager','en','Rename');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'rename_to','filemanager','en','Rename');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'download','filemanager','en','Download');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'upload','filemanager','en','Upload');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'save','filemanager','en','Save');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'exit','filemanager','en','Exit');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'cancel','filemanager','en','Cancel');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'specify_file_name','filemanager','en','You must specify a name for the file you wish to create');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'no_file_name','filemanager','en','No filename was specified');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'err_saving_file','filemanager','en','Error saving file to disk');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'yes','filemanager','en','Yes');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'no','filemanager','en','No');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'no','filemanager','en','No');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'newsgroups','nntp','en','Newsgroups');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'update','nntp','en','Update');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'show all groups','nntp','en','Show All Groups');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'available groups','nntp','en','Available Groups');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'show groups containing','nntp','en','Show Groups Containing');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'next','nntp','en','Next');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'threads','nntp','en','Threads');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'message x','nntp','en','Message %1');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'author','nntp','en','Author');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'subject','nntp','en','Subject');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'date','nntp','en','Date');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'monitor','nntp','en','Monitor');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'monitor','nntp','en','Monitor');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'max matchs per page','preferences','en','Max matches per page');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'time zone offset','preferences','en','Time zone offset');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'this server is located in the x timezone','preferences','en',' timezone');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'date format','preferences','en','Date format');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'time format','preferences','en','Time format');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'language','preferences','en','Language');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'default sorting order','preferences','en','Default sorting order');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'default application','preferences','en','Default application');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'show text on navigation icons','preferences','en','Show text on navigation icons');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'show current users on navigation bar','preferences','en','Show current users on navigation bar');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'show new messages on main screen','preferences','en','Show new messages on main screen');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'email signature','preferences','en','E-Mail signature');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'show birthday reminders on main screen','preferences','en','Show birthday reminiders on main screen');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'show high priority events on main screen','preferences','en','Show high priority events on main screen');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'weekday starts on','preferences','en','Weekday starts on');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'work day starts on','preferences','en','Work day starts on');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'work day ends on','preferences','en','Work day ends on');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'select headline news sites','preferences','en','Select Headline News sites');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'change your password','preferences','en','Change your Password');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'select different theme','preferences','en','Select different Theme');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'change your settings','preferences','en','Change your Settings');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'change your profile','preferences','en','Change your profile');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'enter your new password','preferences','en','Enter your new password');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 're-enter your password','preferences','en','Re-Enter your password');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'the two passwords are not the same','preferences','en','The two passwords are not the same');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'you must enter a password','preferences','en','You must enter a password');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'your current theme is: x','preferences','en','</b>');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'please, select a new theme','preferences','en','Please, select a new theme');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'note: this feature does *not* change your email password. this will need to be done manually.','preferences','en','Note: This feature does *not* change your email password. This will need to be done manually.');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'monitor newsgroups','preferences','en','Monitor Newsgroups');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'monitor newsgroups','preferences','en','Monitor Newsgroups');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'todo list - add','todo','en','todo list - add');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'todo list - edit','todo','en','Todo list - edit');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'todo list','todo','en','Todo list');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'todo','todo','en','todo');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'status','todo','en','Status');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'urgency','todo','en','Urgency');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'completed','todo','en','completed');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'last updated','todo','en','Last Updated');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'access type','todo','en','Access type');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'which groups','todo','en','Which groups');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'clear form','todo','en','Clear form');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'date due','todo','en','Date Due');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'created by','todo','en','Created By');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'you have entered an invailed date','todo','en','you have entered an invailed date');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'are you sure you want to delete this entry','todo','en','Are you sure you want to delete this entry?');
REPLACE INTO lang (message_id, app_name, lang, content) VALUES( 'are you sure you want to delete this entry','todo','en','Are you sure you want to delete this entry?');
