<?php
  /**************************************************************************\
  * phpGroupWare                                                             *
  * http://www.phpgroupware.org                                              *
  * --------------------------------------------                             *
  *  This program is free software; you can redistribute it and/or modify it *
  *  under the terms of the GNU General Public License as published by the   *
  *  Free Software Foundation; either version 2 of the License, or (at your  *
  *  option) any later version.                                              *
  \**************************************************************************/

  /* $Id$ */
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'low','common','en','Low')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'forum','common','en','Forum')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'normal','common','en','Normal')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'medium','common','en','Medium')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'high','common','en','High')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'add','common','en','Add')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'create','common','en','Create')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'edit','common','en','Edit')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'copy','common','en','Copy')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'rename','common','en','Rename')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'delete','common','en','Delete')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'done','common','en','Done')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'change','common','en','Change')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'clear form','common','en','Clear Form')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'total','common','en','Total')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'view','common','en','View')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'save','common','en','Save')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'submit','common','en','Submit')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'search','common','en','Search')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'cancel','common','en','Cancel')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'exit','common','en','Exit')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'yes','common','en','Yes')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'no','common','en','No')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'ok','common','en','OK')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'clear','common','en','Clear')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'january','common','en','January')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'february','common','en','February')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'march','common','en','March')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'april','common','en','April')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'may','common','en','May')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'june','common','en','June')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'july','common','en','July')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'august','common','en','August')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'september','common','en','September')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'october','common','en','October')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'november','common','en','November')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'december','common','en','December')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'monday','common','en','Monday')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'tuesday','common','en','Tuesday')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'wednesday','common','en','Wednesday')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'thursday','common','en','Thursday')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'friday','common','en','Friday')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'saturday','common','en','Saturday')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'sunday','common','en','Sunday')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'access','common','en','Access')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'private','common','en','Private')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'access type','common','en','Access type')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'group access','common','en','Group Access')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'global public','common','en','Global Public')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'group public','common','en','Group Public')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'which groups','common','en','which groups')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'created by','common','en','Created By')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'administration','common','en','Administration')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'inventory','common','en','Inventory')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'todo list','common','en','Todo List')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'calendar','common','en','calendar')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'bookmarks','common','en','Bookmarks')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'addressbook','common','en','Addressbook')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'e-mail','common','en','E-Mail')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'chat','common','en','Chat')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'preferences','common','en','Preferences')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'login','common','en','Login')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'logout','common','en','Logout')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'first name','common','en','First name')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'last name','common','en','Last name')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'admin','common','en','Admin')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'email','common','en','E-Mail')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'headlines','common','en','Headlines')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'nntp','common','en','NNTP')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'groups','common','en','Groups')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'book marks','common','en','Book marks')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'name','common','en','Name')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'file manager','common','en','File manager')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'ftp','common','en','FTP')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'password','common','en','Password')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'date','common','en','Date')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'time','common','en','Time')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'priority','common','en','Priority')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'help','common','en','Help')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'error','common','en','Error')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'updated','common','en','Updated')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'home','common','en','Home')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'users','common','en','users')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'news headlines','common','en','News headlines')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'news reader','common','en','News Reader')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'human resources','common','en','Human Resources')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'address book','common','en','Address Book')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'current users','common','en','Current users')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'first page','common','en','first page')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'next page','common','en','next page')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'last page','common','en','last page')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'previous page','common','en','Previous page')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'filter','common','en','Filter')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'show all','common','en','show all')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'only yours','common','en','only yours')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'print','common','en','Print')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'trouble ticket system','common','en','Trouble Ticket System')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'you are required to change your password during your first login','common','en','You are required to change your password during your first login')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'powered by phpgroupware version x','common','en','Powered by <a href=http://www.phpgroupware.org>phpGroupWare</a> version %1')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'sorry, there was a problem processing your request.','common','en','Sorry, there was a problem processing your request.')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'your message has been sent','common','en','Your message has been sent')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'new entry added sucessfully','common','en','New entry added sucessfully')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'entry updated sucessfully','common','en','Entry updated sucessfully')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'entry has been deleted sucessfully','common','en','Entry has been deleted sucessfully')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'password has been updated','common','en','Password has been updated')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'session has been killed','common','en','Session has been killed')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'account has been updated','common','en','Account has been updated')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'account has been created','common','en','Account has been created')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'account has been deleted','common','en','Account has been deleted')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'error creating x x directory','common','en','Error creating %1%2 directory')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'error deleting x x directory','common','en','Error deleting %1%2 directory')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'error renaming x x directory','common','en','Error renaming %1%2 directory')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'please x by hand','common','en','Please %1 by hand')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'to correct this error for the future you will need to properly set the','common','en','To correct this error for the future you will need to properly set the')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'permissions to the files/users directory','common','en','permissions to the files/users directory')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'On *nix systems please type: x','common','en','On *nix systems please type: %1')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'your settings have been updated','common','en','Your settings have been Updated')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'group has been added','common','en','Group has been added')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'group has been deleted','common','en','Group has been deleted')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'group has been updated','common','en','Group has been updated')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'showing x - x of x','common','en','showing %1 - %2 of %3')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'showing x','common','en','showing %1')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'your search returned 1 match','common','en','your search returned 1 match')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'your search returned x matchs','common','en','your search returned %1 matchs')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'you have 1 new message!','common','en','You have 1 new message!')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'you have x new messages!','common','en','You have %1 new messages!')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'today is x\'s birthday!','common','en','Today is %1\'s birthday!')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'tommorow is x\'s birthday.','common','en','Tommorow is %1\'s birthday.')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'you have 1 high priority event on your calendar today.','common','en','You have 1 high priority event on your calendar today.')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'you have x high priority events on your calendar today.','common','en','You have %1 high priority events on your calendar today.')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'it has been more then x days since you changed your password','common','en','It has been more then %1 days since you changed your password')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'are you sure you want to delete this entry ?','common','en','Are you sure you want to delete this entry ?')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'username','login','en','Username')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'password','login','en','Password')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'login','login','en','Login')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'use cookies','login','en','use cookies')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'you have been successfully logged out','login','en','You have been successfully logged out')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'sorry, your login has expired','login','en','Sorry, your login has expired')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'bad login or password','login','en','Bad login or password')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'your session could not be verified.','login','en','Your session could not be verified.')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'address book','addressbook','en','Address Book')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'last name','addressbook','en','Last Name')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'first name','addressbook','en','First Name')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'e-mail','addressbook','en','E-Mail')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'home phone','addressbook','en','Home Phone')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'fax','addressbook','en','Fax')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'work phone','addressbook','en','Work Phone')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'pager','addressbook','en','Pager')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'mobile','addressbook','en','Mobile')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'other number','addressbook','en','Other Number')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'street','addressbook','en','Street')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'birthday','addressbook','en','Birthday')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'city','addressbook','en','City')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'state','addressbook','en','State')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'zip code','addressbook','en','ZIP Code')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'notes','addressbook','en','Notes')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'company name','addressbook','en','company name')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'last x logins','admin','en','Last %1 logins')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'loginid','admin','en','LoginID')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'ip','admin','en','IP')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'total records','admin','en','Total records')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'user accounts','admin','en','User accounts')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'new group name','admin','en','New group name')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'create group','admin','en','Create Group')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'kill','admin','en','Kill')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'idle','admin','en','idle')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'login time','admin','en','Login Time')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'anonymous user','admin','en','Anonymous user')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'manager','admin','en','Manager')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'account active','admin','en','Account active')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 're-enter password','admin','en','Re-enter password')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'group name','admin','en','Group Name')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'display','admin','en','Display')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'base url','admin','en','Base URL')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'news file','admin','en','News File')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'minutes between reloads','admin','en','Minutes between Reloads')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'listings displayed','admin','en','Listings Displayed')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'news type','admin','en','News Type')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'user groups','admin','en','User groups')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'headline sites','admin','en','Headline Sites')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'network news','admin','en','Network News')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'site','admin','en','Site')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'view sessions','admin','en','View sessions')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'view access log','admin','en','View Access Log')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'active','admin','en','Active')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'disabled','admin','en','Disabled')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'last time read','admin','en','Last Time Read')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'permissions','admin','en','Permissions')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'title','admin','en','Title')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'enabled','admin','en','Enabled')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'applications','admin','en','Applications')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'edit group','admin','en','Edit Group')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'submit changes','admin','en','Submit Changes')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'you must add at least 1 permission to this account','admin','en','You must add at least 1 permission to this account')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'installed applications','admin','en','Installed applications')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'remove all users from this group','admin','en','Remove all users from this group')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'permissions this group has','admin','en','Permissions this group has')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'select permissions this group will have','admin','en','Select permissions this group will have')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'sorry, that group name has already been taking.','admin','en','Sorry, that group name has already been taking.')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'add new application','admin','en','Add new application')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'application name','admin','en','Application name')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'application title','admin','en','Application title')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'edit application','admin','en','Edit application')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'you must enter an application name and title.','admin','en','You must enter an application name and title.')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'are you sure you want to delete this application ?','admin','en','Are you sure you want to delete this application ?')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'are you sure you want to delete this group ?','admin','en','Are you sure you want to delete this group ?')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'are you sure you want to kill this session ?','admin','en','Are you sure you want to kill this session ?')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'all records and account information will be lost!','admin','en','All records and account information will be lost!')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'are you sure you want to delete this account ?','admin','en','Are you sure you want to delete this account ?')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'are you sure you want to delete this news site ?','admin','en','Are you sure you want to delete this news site ?')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'percent of users that logged out','admin','en','Percent of users that logged out')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'list of current users','admin','en','list of current users')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'new password [ leave blank for no change ]','admin','en','New password [ Leave blank for no change ]')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'the two passwords are not the same','admin','en','The two passwords are not the same')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'the login and password can not be the same','admin','en','The login and password can not be the same')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'you must enter a password','admin','en','You must enter a password')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'that loginid has already been taken','admin','en','That loginid has already been taken')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'you must enter a display','admin','en','You must enter a display')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'you must enter a base url','admin','en','You must enter a base url')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'you must enter a news url','admin','en','You must enter a news url')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'you must enter the number of minutes between reload','admin','en','You must enter the number of minutes between reload')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'you must enter the number of listings display','admin','en','You must enter the number of listings display')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'you must select a file type','admin','en','You must select a file type')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'that site has already been entered','admin','en','That site has already been entered')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'select users for inclusion','admin','en','Select users for inclusion')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'sorry, the follow users are still a member of the group x','admin','en','Sorry, the follow users are still a member of the group %1')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'they must be removed before you can continue','admin','en','They must be removed before you can continue')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'today','calendar','en','Today')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'this week','calendar','en','This week')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'this month','calendar','en','This month')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'generate printer-friendly version','calendar','en','Generate printer-friendly version')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'printer friendly','calendar','en','Printer Friendly')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'you have not entered a\\nbrief description','calendar','en','You have not entered a\\nBrief Description')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'you have not entered a\\nvalid time of day.','calendar','en','You have not entered a\\nvalid time of day.')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'are you sure\\nyou want to\\ndelete this entry ?','calendar','en','Are you sure\\nyou want to\\ndelete this entry ?')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'participants','calendar','en','Participants')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'calendar - edit','calendar','en','Calendar - Edit')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'calendar - add','calendar','en','Calendar - Add')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'brief description','calendar','en','Brief Description')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'full description','calendar','en','Full Description')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'duration','calendar','en','Duration')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'minutes','calendar','en','minutes')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'repeat type','calendar','en','Repeat type')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'none','calendar','en','None')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'daily','calendar','en','Daily')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'weekly','calendar','en','weekly')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'monthly (by day)','calendar','en','Monthly (by day)')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'monthly (by date)','calendar','en','Monthly (by date)')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'yearly','calendar','en','Yearly')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'repeat end date','calendar','en','Repeat End date')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'use end date','calendar','en','Use End date')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'repeat day','calendar','en','Repeat day')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( '(for weekly)','calendar','en','(for Weekly)')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'frequency','calendar','en','Frequency')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'sun','calendar','en','Sun')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'mon','calendar','en','Mon')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'tue','calendar','en','Tue')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'wed','calendar','en','Wed')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'thu','calendar','en','Thu')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'fri','calendar','en','Fri')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'sat','calendar','en','Sat')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'su','calendar','en','Su')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'mo','calendar','en','M')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'tu','calendar','en','T')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'we','calendar','en','W')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'th','calendar','en','T')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'fr','calendar','en','F')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'sa','calendar','en','Sa')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'search results','calendar','en','Search Results')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'no matches found.','calendar','en','No matches found.')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( '1 match found','calendar','en','1 match found')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'x matches found','calendar','en','%1 matches found')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'description','calendar','en','Description')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'repetition','calendar','en','Repetition')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'days repeated','calendar','en','days repeated')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'go!','calendar','en','Go!')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'year','calendar','en','Year')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'month','calendar','en','Month')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'week','calendar','en','Week')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'new entry','calendar','en','New Entry')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'view this entry','calendar','en','View this entry')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'the following conflicts with the suggested time:<ul>x</ul>','calendar','en','The following conflicts with the suggested time:<ul>%1</ul>')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'your suggested time of <B> x - x </B> conflicts with the following existing calendar entries:','calendar','en','Your suggested time of <B> %1 - %2 </B> conflicts with the following existing calendar entries:')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'you must enter one or more search keywords','calendar','en','You must enter one or more search keywords')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'are you sure\\nyou want to\\ndelete this entry ?\\n\\nthis will delete\\nthis entry for all users.','calendar','en','Are you sure\\nyou want to\\ndelete this entry ?\\n\\nThis will delete\\nthis entry for all users.')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'a','calendar','en','')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'reply','email','en','Reply')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'reply all','email','en','Reply All')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'forward','email','en','Forward')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'delete','email','en','Delete')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'previous','email','en','Previous')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'next','email','en','Next')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'from','email','en','From')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'to','email','en','To')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'cc','email','en','CC')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'files','email','en','Files')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'date','email','en','Date')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'send','email','en','Send')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'subject','email','en','Subject')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'folder','email','en','Folder')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'size','email','en','Size')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'section','email','en','Section')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'image','email','en','Image')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'no subject','email','en','No Subject')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'compose','email','en','Compose')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'message','email','en','Message')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'messages','email','en','Messages')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'new message','email','en','New message')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'undisclosed sender','email','en','Undisclosed Sender')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'undisclosed recipients','email','en','Undisclosed Recipients')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'please select a message first','email','en','Please select a message first')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'this folder is empty','email','en','This folder is empty')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'switch current folder to','email','en','Switch Current Folder To')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'move selected messages into','email','en','Move Selected Messages into')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'add to addressbook','email','en','Add to addressbook')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( '1 message has been deleted','email','en','1 message has been deleted')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'x messages have been deleted','email','en','%1 messages have been deleted')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'monitor','email','en','Monitor')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'usersfile_perm_error','filemanager','en','To correct this error you will need to properly set the permissions to the files/users directory.<BR> On *nix systems please type: chmod 707')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'groupsfile_perm_error','filemanager','en','To correct this error you will need to properly set the permissions to the files/groups directory.<BR> On *nix systems please type: chmod 707')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'private_files','filemanager','en','Private files')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'group_files','filemanager','en','group files')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'files','filemanager','en','Files')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'new_file','filemanager','en','New File')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'rename_to','filemanager','en','Rename to')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'file_upload','filemanager','en','File Upload')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'current_file','filemanager','en','Current File')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'clipboard_contents','filemanager','en','Clipboard Contents')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'copy_as','filemanager','en','Copy as')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'create','filemanager','en','Create')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'edit','filemanager','en','Edit')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'copy','filemanager','en','Copy')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'delete','filemanager','en','Delete')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'do_delete','filemanager','en','Delete')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'rename','filemanager','en','Rename')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'download','filemanager','en','Download')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'upload','filemanager','en','Upload')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'save','filemanager','en','Save')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'exit','filemanager','en','Exit')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'cancel','filemanager','en','Cancel')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'specify_file_name','filemanager','en','You must specify a name for the file you wish to create')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'no_file_name','filemanager','en','No filename was specified')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'err_saving_file','filemanager','en','Error saving file to disk')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'yes','filemanager','en','Yes')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'no','filemanager','en','No')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'newsgroups','nntp','en','Newsgroups')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'update','nntp','en','Update')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'show all groups','nntp','en','Show All Groups')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'available groups','nntp','en','Available Groups')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'show groups containing','nntp','en','Show Groups Containing')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'next','nntp','en','Next')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'threads','nntp','en','Threads')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'message x','nntp','en','Message %1')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'author','nntp','en','Author')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'subject','nntp','en','Subject')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'date','nntp','en','Date')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'monitor','nntp','en','Monitor')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'max matchs per page','preferences','en','Max matches per page')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'time zone offset','preferences','en','Time zone offset')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'this server is located in the x timezone','preferences','en',' timezone')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'date format','preferences','en','Date format')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'time format','preferences','en','Time format')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'language','preferences','en','Language')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'default sorting order','preferences','en','Default sorting order')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'default application','preferences','en','Default application')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'show text on navigation icons','preferences','en','Show text on navigation icons')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'show current users on navigation bar','preferences','en','Show current users on navigation bar')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'show new messages on main screen','preferences','en','Show new messages on main screen')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'email signature','preferences','en','E-Mail signature')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'show birthday reminders on main screen','preferences','en','Show birthday reminiders on main screen')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'show high priority events on main screen','preferences','en','Show high priority events on main screen')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'weekday starts on','preferences','en','Weekday starts on')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'work day starts on','preferences','en','Work day starts on')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'work day ends on','preferences','en','Work day ends on')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'select headline news sites','preferences','en','Select Headline News sites')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'change your password','preferences','en','Change your Password')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'select different theme','preferences','en','Select different Theme')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'change your settings','preferences','en','Change your Settings')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'change your profile','preferences','en','Change your profile')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'enter your new password','preferences','en','Enter your new password')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 're-enter your password','preferences','en','Re-Enter your password')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'the two passwords are not the same','preferences','en','The two passwords are not the same')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'you must enter a password','preferences','en','You must enter a password')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'your current theme is: x','preferences','en','</b>')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'please, select a new theme','preferences','en','Please, select a new theme')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'note: this feature does *not* change your email password. this will need to be done manually.','preferences','en','Note: This feature does *not* change your email password. This will need to be done manually.')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'monitor newsgroups','preferences','en','Monitor Newsgroups')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'todo list - add','todo','en','todo list - add')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'todo list - edit','todo','en','Todo list - edit')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'todo list','todo','en','Todo list')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'todo','todo','en','todo')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'status','todo','en','Status')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'urgency','todo','en','Urgency')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'completed','todo','en','completed')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'last updated','todo','en','Last Updated')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'access type','todo','en','Access type')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'which groups','todo','en','Which groups')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'clear form','todo','en','Clear form')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'date due','todo','en','Date Due')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'created by','todo','en','Created By')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'you have entered an invailed date','todo','en','you have entered an invailed date')");
  $db->query("INSERT INTO lang (message_id, app_name, lang, content) VALUES( 'are you sure you want to delete this entry','todo','en','Are you sure you want to delete this entry?')");
