<?php
/**
 * EGroupware Api: Test the SimpleSAMLphp configuration generated by Auth\Saml
 *
 * @link https://www.egroupware.org
 * @package api
 * @subpackage test
 * @license http://opensource.org/licenses/gpl-license.php GPL - GNU General Public License
 */

namespace EGroupware\Api\Auth;

require_once __DIR__ . '/../LoggedInTest.php';

use EGroupware\Api;
use EGroupware\Api\LoggedInTest;

/**
 * Saml::checkDefaultConfig() creates config.php and authsources.php by running string replacements over the
 * templates shipped with SimpleSAMLphp. strtr() does NOT complain if a search string no longer exists, so a
 * template change in a SimpleSAMLphp update silently results in a wrong configuration, eg.:
 * - 'session.cookie.domain' => null changed to '' in SimpleSAMLphp 2.x, so SimpleSAMLphp sent a host-only
 *   "sessionid" cookie beside our one with a domain, and the browser sent the old one first
 * - 'entityID' lost its key, which SimpleSAMLphp 2 requires
 *
 * This test generates the configuration and checks the values that matter really got written.
 */
class SamlDefaultConfigTest extends LoggedInTest
{
	protected string $files_dir;
	protected array $old_server = [];
	protected array $old_statics = [];
	protected ?string $old_host = null;
	protected ?string $old_https = null;

	protected function setUp() : void
	{
		parent::setUp();
		$this->files_dir = sys_get_temp_dir().'/saml-config-test-'.uniqid();
		mkdir($this->files_dir);

		$this->old_server = $GLOBALS['egw_info']['server'] ?? [];
		$this->old_host = $_SERVER['HTTP_HOST'] ?? null;
		$this->old_https = $_SERVER['HTTPS'] ?? null;
		$_SERVER['HTTP_HOST'] = 'saml-test.example.org';
		$_SERVER['HTTPS'] = 'on';

		// Session::getCookieDomain() returns nothing in CLI, set the cookie parameters it would return
		$class = new \ReflectionClass(Api\Session::class);
		foreach(['cookie_domain' => 'saml-test.example.org', 'cookie_path' => '/egroupware', 'cookie_secure' => true] as $name => $value)
		{
			$prop = $class->getProperty($name);
			$this->old_statics[$name] = $prop->getValue();
			$prop->setValue(null, $value);
		}
	}

	protected function tearDown() : void
	{
		$GLOBALS['egw_info']['server'] = $this->old_server;
		if (isset($this->old_host)) $_SERVER['HTTP_HOST'] = $this->old_host; else unset($_SERVER['HTTP_HOST']);
		if (isset($this->old_https)) $_SERVER['HTTPS'] = $this->old_https; else unset($_SERVER['HTTPS']);

		$class = new \ReflectionClass(Api\Session::class);
		foreach($this->old_statics as $name => $value)
		{
			$class->getProperty($name)->setValue(null, $value);
		}
		exec('rm -rf '.escapeshellarg($this->files_dir));
		parent::tearDown();
	}

	protected function config() : array
	{
		return [
			'files_dir' => $this->files_dir,
			'webserver_url' => '/egroupware',
			'saml_idp' => 'https://idp.example.org/idp/shibboleth',
			'saml_username' => 'emailAddress',
			'saml_sp' => 'EGroupware Test',
			'saml_contact_name' => 'Admin',
			'saml_contact_email' => 'admin@example.org',
		];
	}

	protected function generated(string $file) : string
	{
		$path = $this->files_dir.'/saml/'.$file;
		$this->assertFileExists($path);
		return file_get_contents($path);
	}

	public function testGeneratedConfigPhp()
	{
		Saml::checkDefaultConfig($this->config());

		$config = $this->generated('config.php');
		$this->assertValidPhp($this->files_dir.'/saml/config.php');

		// session cookie MUST be the one EGroupware uses (name, domain, path and secure), otherwise the browser has
		// two cookies "sessionid" and sends the old one first
		$this->assertMatchesRegularExpression("/^\\s*'session\\.cookie\\.name' => 'sessionid',/m", $config);
		$this->assertMatchesRegularExpression("/^\\s*'session\\.phpsession\\.cookiename' => 'sessionid',/m", $config);
		$this->assertMatchesRegularExpression("/^\\s*'session\\.cookie\\.domain' => '\\.saml-test\\.example\\.org',/m", $config,
			"'session.cookie.domain' is not set, template changed?");
		$this->assertMatchesRegularExpression("#^\\s*'session\\.cookie\\.path' => '/egroupware',#m", $config);
		$this->assertMatchesRegularExpression("/^\\s*'session\\.cookie\\.secure' => true,/m", $config,
			"'session.cookie.secure' is not set, template changed?");

		$this->assertMatchesRegularExpression("#^\\s*'baseurlpath' => 'https://saml-test\\.example\\.org/egroupware/saml/',#m", $config);
		$this->assertMatchesRegularExpression("/^\\s*'metadata\\.sign\\.privatekey' => 'saml\\.pem',/m", $config);
		$this->assertMatchesRegularExpression("/^\\s*'metadata\\.sign\\.certificate' => 'saml\\.crt',/m", $config);
	}

	public function testGeneratedAuthsourcesPhp()
	{
		Saml::checkDefaultConfig($this->config());

		$authsources = $this->generated('authsources.php');
		$this->assertValidPhp($this->files_dir.'/saml/authsources.php');

		// SimpleSAMLphp 2 requires the key "entityID"
		$this->assertMatchesRegularExpression("#^\\s*'entityID' => 'https://saml-test\\.example\\.org/',#m", $authsources,
			"'entityID' is missing or lost its key, template changed?");
		$this->assertMatchesRegularExpression("#^\\s*'idp' => 'https://idp\\.example\\.org/idp/shibboleth',#m", $authsources);
		$this->assertMatchesRegularExpression("/^\\s*'privatekey' => 'saml\\.pem',/m", $authsources);
		$this->assertStringContainsString("'eduPersonPrincipalName' => 'urn:oid:1.3.6.1.4.1.5923.1.1.1.6'", $authsources);
		$this->assertStringNotContainsString("'eduPersonPricipalName'", $authsources);
		$this->assertMatchesRegularExpression("/^\\s*'certificate' => 'saml\\.crt',/m", $authsources);
		$this->assertFileExists($this->files_dir.'/saml/cert/saml.pem');
		$this->assertFileExists($this->files_dir.'/saml/cert/saml.crt');
	}

	/**
	 * Existing installs have a config created from the old / wrong replacements, they get repaired on a setup save
	 */
	public function testUpdateConfigRepairsOldFiles()
	{
		Saml::checkDefaultConfig($this->config());

		// simulate what we generated before: host-only cookie, no secure flag and entityID without key
		$config_php = $this->files_dir.'/saml/config.php';
		$authsources_php = $this->files_dir.'/saml/authsources.php';
		file_put_contents($config_php, preg_replace(
			["/^(\\s*'session\\.cookie\\.domain' => ).*?$/m", "/^(\\s*)'session\\.cookie\\.secure' => true,$/m"],
			["$1'',", "$1//'session.cookie.secure' => true,"], file_get_contents($config_php)));
		file_put_contents($authsources_php, str_replace(["'entityID' => 'https", "'eduPersonPrincipalName'=>"], ["'https", "'eduPersonPricipalName'=>"],
			file_get_contents($authsources_php)));
		$this->assertStringNotContainsString("'.saml-test.example.org'", file_get_contents($config_php));
		$this->assertStringNotContainsString("'entityID'", file_get_contents($authsources_php));

		Saml::updateConfig($this->config());

		$this->assertValidPhp($config_php);
		$this->assertValidPhp($authsources_php);
		$this->assertMatchesRegularExpression("/^\\s*'session\\.cookie\\.domain' => '\\.saml-test\\.example\\.org',/m", file_get_contents($config_php));
		$this->assertMatchesRegularExpression("/^\\s*'session\\.cookie\\.secure' => true,/m", file_get_contents($config_php));
		$this->assertMatchesRegularExpression("#^\\s*'entityID' => 'https://saml-test\\.example\\.org/',#m", file_get_contents($authsources_php));
		$this->assertStringNotContainsString("'eduPersonPricipalName'", file_get_contents($authsources_php));
		$this->assertMatchesRegularExpression("/'eduPersonPrincipalName' *=> *'urn:oid:1\\.3\\.6\\.1\\.4\\.1\\.5923\\.1\\.1\\.1\\.6'/", file_get_contents($authsources_php));
	}

	protected function assertValidPhp(string $path)
	{
		exec(escapeshellarg(PHP_BINARY).' -l '.escapeshellarg($path).' 2>&1', $output, $rc);
		$this->assertSame(0, $rc, "$path is no valid PHP: ".implode("\n", $output));
	}
}
