INSERT INTO lang VALUES ('info','common','de','InfoLog');
INSERT INTO lang VALUES ('urgency','info','de','Priorität');
INSERT INTO lang VALUES ('sub','info','de','Teil-<br>projekte');
INSERT INTO lang VALUES ('add sub','info','de','neues Teilprojekt anlegen');
INSERT INTO lang VALUES ('view subs','info','de','Teilprojekte anzeigen');
INSERT INTO lang VALUES ('type','info','de','Typ');
INSERT INTO lang VALUES ('urgent','info','de','Dringend');
INSERT INTO lang VALUES ('confirm','info','de','Bestätigung');
INSERT INTO lang VALUES ('not','info','de','keine');
INSERT INTO lang VALUES ('done','info','de','erledigt');
INSERT INTO lang VALUES ('accept','info','de','bei Annahme');
INSERT INTO lang VALUES ('both','info','de','Annahme+erledigt');
INSERT INTO lang VALUES ('offer','info','de','Angebot');
INSERT INTO lang VALUES ('ongoing','info','de','in Arbeit');
INSERT INTO lang VALUES ('call','info','de','anrufen');
INSERT INTO lang VALUES ('will-call','info','de','ruft zurück');
INSERT INTO lang VALUES ('billed','info','de','abgerechnet');
INSERT INTO lang VALUES ('finish','info','de','wenn erledigt');
INSERT INTO lang VALUES ('from','info','de','Von');
INSERT INTO lang VALUES ('phone/email','info','de','Telefon/Email');
INSERT INTO lang VALUES ('note','info','de','Notiz');
INSERT INTO lang VALUES ('fax','info','de','Fax');
INSERT INTO lang VALUES ('task','info','de','Auftrag');
INSERT INTO lang VALUES ('phone','info','de','Anruf');
INSERT INTO lang VALUES ('reject','info','de','Absage');
INSERT INTO lang VALUES ('not assigned','info','de','nicht zugewiesen');
INSERT INTO lang VALUES ('responsible','info','de','Auftrag an');
INSERT INTO lang VALUES ('duration','info','de','Dauer');
INSERT INTO lang VALUES ('days','info','de','Tage');
INSERT INTO lang VALUES ('today','info','de','Heute');
INSERT INTO lang VALUES ('startdate','info','de','Startdatum');
INSERT INTO lang VALUES ('enddate','info','de','Enddatum');
INSERT INTO lang VALUES ('info log - edit','info','de','Info Log - Bearbeiten');
INSERT INTO lang VALUES ('info log','info','de','Info Log');
INSERT INTO lang VALUES ('info log - delete','info','de','Info Log - Löschen');
INSERT INTO lang VALUES ('are you sure you want to delete this entry','info','de','Sind Sie sicher, dass Sie diesen Eintrag löschen wollen?');
INSERT INTO lang VALUES ('phonecall','info','de','Telefonanruf');
INSERT INTO lang VALUES ('no - cancel','info','de','Nein - Abbruch');
INSERT INTO lang VALUES ('yes - delete','info','de','Ja - Löschen');
INSERT INTO lang VALUES ('info log - new','info','de','Info Log - Anlegen');
INSERT INTO lang VALUES ('info log - new subproject','info','de','Info Log - Anlegen Teilprojekt');
INSERT INTO lang VALUES ('re:','info','de','Re: ');
INSERT INTO lang VALUES ('info log - subprojects from','info','de','Info Log - Teilprojekte von');
INSERT INTO lang VALUES ('back to projectlist','info','de','Zurück zur Gesamtliste');
INSERT INTO lang VALUES ('view other subs','info','de','andere Teileprojekte anzeigen');
INSERT INTO lang VALUES ('action','info','de','Befehle');
INSERT INTO lang VALUES ('showing x - x of x','info','de','Einträge %1 - %2 von %3');
INSERT INTO lang VALUES ('datecreated','info','de','Erstellt am');
INSERT INTO lang VALUES ('you have entered an invalid ending date','info','de','Sie haben ein ungültiges Enddatum angegeben');
INSERT INTO lang VALUES ('you have entered an invalid starting date','info','de','Sie haben ein ungültiges Startdatum eingegeben');
INSERT INTO lang VALUES ('owner','info','de','Erstellt von');
INSERT INTO lang VALUES ('no entrys found for %1, try again ...','info','de','Keine Einträge für %1 gefunden, nochmal versuchen ...');
INSERT INTO lang VALUES ('search for:','info','de','Suchen nach:');
INSERT INTO lang VALUES ('project','info','de','Projekt');
INSERT INTO lang VALUES ('pattern for search in addressbook','info','de','Muster für Suche im Adressbuch');
INSERT INTO lang VALUES ('pattern for search in projects','info','de','Muster für Suche des Projekts');
INSERT INTO lang VALUES ('not set, use button to search for','info','de','nicht gesetzt, Button zum Suchen verwenden');
INSERT INTO lang VALUES ('import csv-file into info log','info','de','Import CSV-Datei ins Info Log');
INSERT INTO lang VALUES ('csv-fieldname','info','de','CSV-Feldname');
INSERT INTO lang VALUES ('info log-fieldname','info','de','Info Log-Feldname');
INSERT INTO lang VALUES ('translation','info','de','Translation');
INSERT INTO lang VALUES ('import','info','de','Import');
INSERT INTO lang VALUES ('startrecord','info','de','Startdatensatz');
INSERT INTO lang VALUES ('number of records to read (<=200)','info','de','Anzahl Datensätze lesen (<=200)');
INSERT INTO lang VALUES ('test import (show importable records <u>only</u> in browser)','info','de','Test Import (zeige importierbare Datensätze <u>nur</u> im Browser)');
INSERT INTO lang VALUES ('csv-filename','info','de','CSV-Dateiname');
INSERT INTO lang VALUES ('fieldseparator','info','de','Feldbegrenzer');
INSERT INTO lang VALUES ('download','info','de','Datei laden');
INSERT INTO lang VALUES ('%1 records imported','info','de','%1 Datensätze importiert');
INSERT INTO lang VALUES ('%1 records read (not yet imported, you may go back and uncheck test import)','info','de','%1 Datensätze gelesen (noch nicht importiert, sie können %2zurück%3 gehen und Test Import ausschalten)');
INSERT INTO lang VALUES ('%1 records read (not yet imported, you may go back and uncheck test import)','info','en','%1 records read (not yet imported, you may go %2back%3 and uncheck Test Import)');
