INSERT INTO lang VALUES ('infolog','common','de','InfoLog');
INSERT INTO lang VALUES ('urgency','infolog','de','Priorität');
INSERT INTO lang VALUES ('sub','infolog','de','Teil-<br>projekte');
INSERT INTO lang VALUES ('add sub','infolog','de','neues Teilprojekt anlegen');
INSERT INTO lang VALUES ('view subs','infolog','de','Teilprojekte anzeigen');
INSERT INTO lang VALUES ('type','infolog','de','Typ');
INSERT INTO lang VALUES ('urgent','infolog','de','Dringend');
INSERT INTO lang VALUES ('confirm','infolog','de','Bestätigung');
INSERT INTO lang VALUES ('not','infolog','de','keine');
INSERT INTO lang VALUES ('done','infolog','de','erledigt');
INSERT INTO lang VALUES ('accept','infolog','de','bei Annahme');
INSERT INTO lang VALUES ('both','infolog','de','Annahme+erledigt');
INSERT INTO lang VALUES ('offer','infolog','de','Angebot');
INSERT INTO lang VALUES ('ongoing','infolog','de','in Arbeit');
INSERT INTO lang VALUES ('call','infolog','de','anrufen');
INSERT INTO lang VALUES ('will-call','infolog','de','ruft zurück');
INSERT INTO lang VALUES ('billed','infolog','de','abgerechnet');
INSERT INTO lang VALUES ('finish','infolog','de','wenn erledigt');
INSERT INTO lang VALUES ('from','infolog','de','Von');
INSERT INTO lang VALUES ('phone/email','infolog','de','Telefon/Email');
INSERT INTO lang VALUES ('note','infolog','de','Notiz');
INSERT INTO lang VALUES ('fax','infolog','de','Fax');
INSERT INTO lang VALUES ('task','infolog','de','Auftrag');
INSERT INTO lang VALUES ('phone','infolog','de','Anruf');
INSERT INTO lang VALUES ('reject','infolog','de','Absage');
INSERT INTO lang VALUES ('not assigned','infolog','de','nicht zugewiesen');
INSERT INTO lang VALUES ('responsible','infolog','de','Auftrag an');
INSERT INTO lang VALUES ('duration','infolog','de','Dauer');
INSERT INTO lang VALUES ('days','infolog','de','Tage');
INSERT INTO lang VALUES ('today','infolog','de','Heute');
INSERT INTO lang VALUES ('startdate','infolog','de','Startdatum');
INSERT INTO lang VALUES ('enddate','infolog','de','Enddatum');
INSERT INTO lang VALUES ('info log - edit','infolog','de','Info Log - Bearbeiten');
INSERT INTO lang VALUES ('info log','infolog','de','Info Log');
INSERT INTO lang VALUES ('info log - delete','infolog','de','Info Log - Löschen');
INSERT INTO lang VALUES ('are you sure you want to delete this entry','infolog','de','Sind Sie sicher, dass Sie diesen Eintrag löschen wollen?');
INSERT INTO lang VALUES ('phonecall','infolog','de','Telefonanruf');
INSERT INTO lang VALUES ('no - cancel','infolog','de','Nein - Abbruch');
INSERT INTO lang VALUES ('yes - delete','infolog','de','Ja - Löschen');
INSERT INTO lang VALUES ('info log - new','infolog','de','Info Log - Anlegen');
INSERT INTO lang VALUES ('info log - new subproject','infolog','de','Info Log - Anlegen Teilprojekt');
INSERT INTO lang VALUES ('re:','infolog','de','Re: ');
INSERT INTO lang VALUES ('info log - subprojects from','infolog','de','Info Log - Teilprojekte von');
INSERT INTO lang VALUES ('back to projectlist','infolog','de','Zurück zur Gesamtliste');
INSERT INTO lang VALUES ('view other subs','infolog','de','andere Teileprojekte anzeigen');
INSERT INTO lang VALUES ('action','infolog','de','Befehle');
INSERT INTO lang VALUES ('showing x - x of x','infolog','de','Einträge %1 - %2 von %3');
INSERT INTO lang VALUES ('datecreated','infolog','de','Erstellt am');
INSERT INTO lang VALUES ('you have entered an invalid ending date','infolog','de','Sie haben ein ungültiges Enddatum angegeben');
INSERT INTO lang VALUES ('you have entered an invalid starting date','infolog','de','Sie haben ein ungültiges Startdatum eingegeben');
INSERT INTO lang VALUES ('owner','infolog','de','Erstellt von');
INSERT INTO lang VALUES ('no entrys found for %1, try again ...','infolog','de','Keine Einträge für %1 gefunden, nochmal versuchen ...');
INSERT INTO lang VALUES ('search for:','infolog','de','Suchen nach:');
INSERT INTO lang VALUES ('project','infolog','de','Projekt');
INSERT INTO lang VALUES ('pattern for search in addressbook','infolog','de','Muster für Suche im Adressbuch');
INSERT INTO lang VALUES ('pattern for search in projects','infolog','de','Muster für Suche des Projekts');
INSERT INTO lang VALUES ('not set, use button to search for','infolog','de','nicht gesetzt, Button zum Suchen verwenden');
INSERT INTO lang VALUES ('import csv-file into info log','infolog','de','Import CSV-Datei ins Info Log');
INSERT INTO lang VALUES ('csv-fieldname','infolog','de','CSV-Feldname');
INSERT INTO lang VALUES ('info log-fieldname','infolog','de','Info Log-Feldname');
INSERT INTO lang VALUES ('translation','infolog','de','Translation');
INSERT INTO lang VALUES ('import','infolog','de','Import');
INSERT INTO lang VALUES ('startrecord','infolog','de','Startdatensatz');
INSERT INTO lang VALUES ('number of records to read (<=200)','infolog','de','Anzahl Datensätze lesen (<=200)');
INSERT INTO lang VALUES ('test import (show importable records <u>only</u> in browser)','infolog','de','Test Import (zeige importierbare Datensätze <u>nur</u> im Browser)');
INSERT INTO lang VALUES ('csv-filename','infolog','de','CSV-Dateiname');
INSERT INTO lang VALUES ('fieldseparator','infolog','de','Feldbegrenzer');
INSERT INTO lang VALUES ('download','infolog','de','Datei laden');
INSERT INTO lang VALUES ('%1 records imported','infolog','de','%1 Datensätze importiert');
INSERT INTO lang VALUES ('%1 records read (not yet imported, you may go back and uncheck test import)','infolog','de','%1 Datensätze gelesen (noch nicht importiert, sie können %2zurück%3 gehen und Test Import ausschalten)');
INSERT INTO lang VALUES ('%1 records read (not yet imported, you may go back and uncheck test import)','infolog','en','%1 records read (not yet imported, you may go %2back%3 and uncheck Test Import)');
